apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-image-renderer
  namespace: monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: grafana-image-renderer
    creationPolicy: Owner
  data:
    - secretKey: auth-token
      remoteRef:
        key: /demo-eks-dev/image-render/grafana_image_render_auth_token
