apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-data
  namespace: monitor
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
