apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitor
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-internal:9090
        isDefault: true
      - name: Loki
        uid: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: dev-uat
      - name: Loki-Prod
        uid: Loki-Prod
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: prod-tenant
