apiVersion: batch/v1
kind: CronJob
metadata:
  name: rotate-mongo-root-user
  namespace: dev
spec:
  schedule: "15 3 1 * *"
  timeZone: "Asia/Ho_Chi_Minh"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: mongo-credential-rotator
          restartPolicy: Never
          containers:
            - name: rotate-root
              image: mongo:8.0.23
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - /scripts/rotate-root.sh
              env:
                - name: SSM_PREFIX
                  value: /demo-eks-dev/mongo
                - name: AWS_REGION
                  value: us-east-1
                - name: NAMESPACE
                  value: dev
                - name: MONGO_HOST
                  value: mongo:27017
                - name: MONGO_INITDB_ROOT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mongo-root-secret
                      key: MONGO_INITDB_ROOT_USERNAME
                - name: MONGO_INITDB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongo-root-secret
                      key: MONGO_INITDB_ROOT_PASSWORD
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              volumeMounts:
                - name: script
                  mountPath: /scripts
          volumes:
            - name: script
              configMap:
                name: mongo-root-rotate-script
                defaultMode: 0755
