apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-root-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: mongo-root-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: /demo-eks-dev/mongo/root_username
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: /demo-eks-dev/mongo/root_password
