{
 "title": "React App Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uat Backend API logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"uat\", app=\"backend\"}"
    }
   ]
  },
  {
   "title": "Uat Frontend logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"uat\", app=\"frontend\"}"
    }
   ]
  },
  {
   "title": "Uat MongoDB logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"uat\", app=\"mongo\"}"
    }
   ]
  }
 ]
}