services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile-local
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile-local
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 3000
  mongo:
    container_name: mongo
    restart: always
    image: ${MONGO_IMAGE:-mongo:8.0.23}
    env_file:
      - .env
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=1
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo:

volumes:
  mongo_data:
