apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-basic-auth
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: prometheus-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: /demo-eks-dev/prometheus/basic-auth
